//------------------------------------------------------------------------------
// <copyright file="DebugMessageEventArgs.cs" company="Microsoft">
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// </copyright>
//------------------------------------------------------------------------------
using System;

namespace Microsoft.Azure.Kinect.Sensor
{
    /// <summary>
    /// Represents a debug message from the Azure Kinect Sensor SDK.
    /// </summary>
    public class DebugMessageEventArgs : EventArgs
    {
        /// <summary>
        /// Gets or sets the log level of this debug message.
        /// </summary>
        public LogLevel LogLevel { get; set; }

        /// <summary>
        /// Gets or sets the file name of the source file that generated the message.
        /// </summary>
        public string FileName { get; set; }

        /// <summary>
        /// Gets or sets the line number of the source file that generated the message.
        /// </summary>
        public int Line { get; set; }

        /// <summary>
        /// Gets or sets the message generated by the Azure Kinect Sensor SDK.
        /// </summary>
        public string Message { get; set; }
    }
}
